// Copyright (c) 2026 kurnakovv
// This file is licensed under the MIT License.
// See the LICENSE file in the project root for full license information.

using System.Text.RegularExpressions;
using Biak.ConsoleApp.Constants;
using Biak.ConsoleApp.Helpers.Baseline;

namespace Biak.ConsoleApp.Helpers;

/// <summary>
/// `dotnet biak warnings-baseline sync` command helper.
/// </summary>
public static class WarningsBaselineSyncHelper
{
    private static readonly string s_newMarkerRegexText =
        Regex.Escape(WarningsBaselineInitCommandConstant.BASELINE_DIAGNOSTIC_MARKER)
            .Replace("\\ ", "[\\t ]*", StringComparison.OrdinalIgnoreCase);

    private static readonly string s_legacyMarkerRegexText =
        Regex.Escape(WarningsBaselineInitCommandConstant.LEGACY_BASELINE_DIAGNOSTIC_MARKER)
            .Replace("\\ ", "[\\t ]*", StringComparison.OrdinalIgnoreCase);

    private static readonly string s_baselineMarkerRegexText =
        "(?:" + s_newMarkerRegexText + "|" + s_legacyMarkerRegexText + ")";

    private static readonly string s_baselineDiagnosticRegexText =
        @"dotnet_diagnostic\.([A-Z][A-Z0-9]*)\.severity[^\r\n]*" + s_baselineMarkerRegexText;

    private static readonly Regex s_baselineDiagnosticRegex = new(
        @"^\s*" + s_baselineDiagnosticRegexText,
        RegexOptions.Compiled | RegexOptions.IgnoreCase
    );

    private static readonly Regex s_allBaselineCodesRegex = new(
        s_baselineDiagnosticRegexText,
        RegexOptions.Compiled | RegexOptions.IgnoreCase
    );

    /// <summary>
    /// Returns all unique diagnostic codes that appear in baseline entries inside <paramref name="content"/>.
    /// </summary>
    /// <param name="content">.editorconfig content.</param>
    /// <returns>Unique diagnostic codes from baseline entries.</returns>
    public static HashSet<string> GetDiagnosticCodes(string content)
    {
        return s_allBaselineCodesRegex.Matches(content)
            .Select(m => m.Groups[1].Value)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Returns <see langword="true"/> when content contains either new or legacy baseline marker.
    /// </summary>
    /// <param name="content">.editorconfig content.</param>
    /// <returns><see langword="true"/> when baseline marker exists.</returns>
    public static bool HasAnyMarker(string content)
    {
        return content.Contains(WarningsBaselineInitCommandConstant.BASELINE_DIAGNOSTIC_MARKER, StringComparison.Ordinal)
            || content.Contains(WarningsBaselineInitCommandConstant.LEGACY_BASELINE_DIAGNOSTIC_MARKER, StringComparison.Ordinal);
    }

    /// <summary>
    /// Switches baseline severities between <c>suggestion</c> and <c>warning</c>
    /// for lines marked with baseline marker.
    /// </summary>
    /// <param name="content">.editorconfig content.</param>
    /// <param name="activate">
    /// <see langword="true"/> to replace <c>suggestion</c> with <c>warning</c>;
    /// <see langword="false"/> to replace <c>warning</c> with <c>suggestion</c>.
    /// </param>
    /// <returns>Updated content with baseline severities switched for the sync flow.</returns>
    public static string SetSeveritiesForBuild(string content, bool activate)
    {
        string activated = ReplaceSeverity(content, activate, WarningsBaselineInitCommandConstant.BASELINE_DIAGNOSTIC_MARKER);
        return ReplaceSeverity(activated, activate, WarningsBaselineInitCommandConstant.LEGACY_BASELINE_DIAGNOSTIC_MARKER);
    }

    /// <summary>
    /// Removes baseline blocks (<c>[{&lt;files&gt;}]</c> header + diagnostic line + trailing blank lines)
    /// when their diagnostic code is not present in <paramref name="codesToKeep"/>.
    /// <para>
    /// When <paramref name="activeFilesByCode"/> is provided, each kept block is additionally
    /// trimmed to only files that still produce this warning code. If no files remain, the whole
    /// block is removed.
    /// </para>
    /// <para>
    /// A "baseline block" is a <c>[{...}]</c> section header immediately followed (ignoring blank lines)
    /// by a line that ends with <c># ^biak^ baseline</c>. Only blocks in the format generated by
    /// <c>warnings-baseline init</c> are matched; manually created multi-property sections are left untouched.
    /// </para>
    /// </summary>
    /// <param name="content">.editorconfig content.</param>
    /// <param name="codesToKeep">Diagnostic codes that should remain in the baseline.</param>
    /// <param name="activeFilesByCode">
    /// Optional map of active warning files per diagnostic code (normalized as forward-slash paths).
    /// </param>
    /// <returns>Content with resolved baseline blocks/files removed.</returns>
    public static string RemoveFilters(
        string content,
        IReadOnlySet<string> codesToKeep,
        IReadOnlyDictionary<string, IReadOnlySet<string>>? activeFilesByCode = null
    )
    {
        return BaselineSyncEditorconfigHelper.RemoveFilters(
            content,
            codesToKeep,
            TryGetCode,
            activeFilesByCode
        );
    }

    /// <summary>
    /// Returns the files and diagnostic codes that should be synchronized after baseline cleanup.
    /// </summary>
    /// <param name="content">.editorconfig content.</param>
    /// <param name="codesToKeep">Diagnostic codes that should remain in the baseline.</param>
    /// <param name="activeFilesByCode">
    /// Optional map of active warning files per diagnostic code (normalized as forward-slash paths).
    /// </param>
    /// <returns>
    /// Map where key is section file path from baseline entries and value is diagnostic codes
    /// that were removed by code filtering or file-level synchronization.
    /// </returns>
    public static IReadOnlyDictionary<string, IReadOnlySet<string>> GetSynchronizedFiles(
        string content,
        IReadOnlySet<string> codesToKeep,
        IReadOnlyDictionary<string, IReadOnlySet<string>>? activeFilesByCode = null)
    {
        return BaselineSyncEditorconfigHelper.GetSynchronizedFiles(
            content,
            codesToKeep,
            TryGetCode,
            activeFilesByCode
        );
    }

    private static string? TryGetCode(string line)
    {
        Match match = s_baselineDiagnosticRegex.Match(line);
        return match.Success
            ? match.Groups[1].Value
            : null;
    }

    private static string ReplaceSeverity(string content, bool activate, string marker)
    {
        return activate
            ? content.Replace(
                $"= suggestion {marker}",
                $"= warning {marker}",
                StringComparison.Ordinal
            )
            : content.Replace(
                $"= warning {marker}",
                $"= suggestion {marker}",
                StringComparison.Ordinal
            );
    }
}
