// Copyright (c) 2026 kurnakovv
// This file is licensed under the MIT License.
// See the LICENSE file in the project root for full license information.

using System.Text.RegularExpressions;

namespace Biak.ConsoleApp.Helpers;

/// <summary>
/// `dotnet biak warnings-baseline sync` command helper.
/// </summary>
public static class WarningsBaselineSyncHelper
{
    private const string BASELINE_DIAGNOSTIC_REGEXT = @"dotnet_diagnostic\.([A-Z][A-Z0-9]*)\.severity[^\r\n]*#\s*\^biak\^\s*baseline";

    // Matches a [{ ... }] section header that marks a baseline block and captures the file list.
    private static readonly Regex s_baselineSectionHeaderRegex = new(
        @"^\[\{(?<files>[^\}]+)\}\]\s*$",
        RegexOptions.Compiled
    );

    // Matches a dotnet_diagnostic baseline line and captures the diagnostic code.
    private static readonly Regex s_baselineDiagnosticRegex = new(@"^\s*" + BASELINE_DIAGNOSTIC_REGEXT, RegexOptions.Compiled);

    // Matches all diagnostic codes referenced in baseline entries anywhere in the content.
    private static readonly Regex s_allBaselineCodesRegex = new(BASELINE_DIAGNOSTIC_REGEXT, RegexOptions.Compiled);

    /// <summary>
    /// Returns <see langword="true"/> when <paramref name="filePath"/> resolves to a location
    /// inside <paramref name="baseDirectory"/> (directory-traversal protection).
    /// </summary>
    /// <param name="filePath">Path to validate.</param>
    /// <param name="baseDirectory">Base directory that the path must stay within.</param>
    /// <returns><see langword="true"/> when the path is safe; otherwise <see langword="false"/>.</returns>
    public static bool IsPathSafe(string filePath, string baseDirectory)
    {
        string fullBase = Path.GetFullPath(baseDirectory)
            .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
            + Path.DirectorySeparatorChar;

        string fullFile = Path.GetFullPath(filePath, baseDirectory);

        return fullFile.StartsWith(fullBase, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Returns all unique diagnostic codes that appear in baseline entries inside <paramref name="content"/>.
    /// </summary>
    /// <param name="content">.editorconfig content.</param>
    /// <returns>Unique diagnostic codes from baseline entries.</returns>
    public static HashSet<string> GetBaselineDiagnosticCodes(string content)
    {
        return s_allBaselineCodesRegex.Matches(content)
            .Select(m => m.Groups[1].Value)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Switches baseline severities between <c>suggestion</c> and <c>warning</c>
    /// for lines marked with <c># ^biak^ baseline</c>.
    /// </summary>
    /// <param name="content">.editorconfig content.</param>
    /// <param name="activate">
    /// <see langword="true"/> to replace <c>suggestion</c> with <c>warning</c>;
    /// <see langword="false"/> to replace <c>warning</c> with <c>suggestion</c>.
    /// </param>
    /// <returns>Updated content with baseline severities switched for the sync flow.</returns>
    public static string SetBaselineForBuild(string content, bool activate)
    {
        return activate
            ? content.Replace(
                "= suggestion # ^biak^ baseline",
                "= warning # ^biak^ baseline",
                StringComparison.Ordinal
            )
            : content.Replace(
                "= warning # ^biak^ baseline",
                "= suggestion # ^biak^ baseline",
                StringComparison.Ordinal
            );
    }

    /// <summary>
    /// Removes baseline blocks (<c>[{&lt;files&gt;}]</c> header + diagnostic line + trailing blank lines)
    /// when their diagnostic code is not present in <paramref name="codesToKeep"/>.
    /// <para>
    /// When <paramref name="activeFilesByCode"/> is provided, each kept block is additionally
    /// trimmed to only files that still produce this warning code. If no files remain, the whole
    /// block is removed.
    /// </para>
    /// <para>
    /// A "baseline block" is a <c>[{...}]</c> section header immediately followed (ignoring blank lines)
    /// by a line that ends with <c># ^biak^ baseline</c>. Only blocks in the format generated by
    /// <c>warnings-baseline init</c> are matched; manually created multi-property sections are left untouched.
    /// </para>
    /// </summary>
    /// <param name="content">.editorconfig content.</param>
    /// <param name="codesToKeep">Diagnostic codes that should remain in the baseline.</param>
    /// <param name="activeFilesByCode">
    /// Optional map of active warning files per diagnostic code (normalized as forward-slash paths).
    /// </param>
    /// <returns>Content with resolved baseline blocks/files removed.</returns>
    public static string RemoveBaselineFilters(
        string content,
        IReadOnlySet<string> codesToKeep,
        IReadOnlyDictionary<string, IReadOnlySet<string>>? activeFilesByCode = null)
    {
        string newline = content.Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";
        string[] lines = content.Split(new[] { newline }, StringSplitOptions.None);
        Dictionary<int, BaselineBlock> blocksByHeaderIndex = EnumerateBaselineBlocks(lines)
            .ToDictionary(x => x.HeaderIndex);

        List<string> result = new(lines.Length);
        int i = 0;

        while (i < lines.Length)
        {
            string line = lines[i];

            if (blocksByHeaderIndex.TryGetValue(i, out BaselineBlock block))
            {
                if (!codesToKeep.Contains(block.Code))
                {
                    i = block.BlockEndIndex;
                    continue;
                }

                if (activeFilesByCode is not null)
                {
                    IReadOnlySet<string> activeFilesForCode = GetActiveFilesForCode(activeFilesByCode, block.Code);
                    string[] filesToKeep = block.SectionFiles
                        .Where(x => activeFilesForCode.Contains(NormalizeEditorConfigPath(x)))
                        .ToArray();

                    if (filesToKeep.Length == 0)
                    {
                        i = block.BlockEndIndex;
                        continue;
                    }

                    if (filesToKeep.Length != block.SectionFiles.Length)
                    {
                        line = "[{" + string.Join(",", filesToKeep) + "}]";
                    }
                }
            }

            result.Add(line);
            i++;
        }

        return string.Join(newline, result);
    }

    /// <summary>
    /// Returns the files and diagnostic codes that should be synchronized after baseline cleanup.
    /// </summary>
    /// <param name="content">.editorconfig content.</param>
    /// <param name="codesToKeep">Diagnostic codes that should remain in the baseline.</param>
    /// <param name="activeFilesByCode">
    /// Optional map of active warning files per diagnostic code (normalized as forward-slash paths).
    /// </param>
    /// <returns>
    /// Map where key is section file path from baseline entries and value is diagnostic codes
    /// that were removed by code filtering or file-level synchronization.
    /// </returns>
    public static IReadOnlyDictionary<string, IReadOnlySet<string>> GetSynchronizedFiles(
        string content,
        IReadOnlySet<string> codesToKeep,
        IReadOnlyDictionary<string, IReadOnlySet<string>>? activeFilesByCode = null)
    {
        string newline = content.Contains("\r\n", StringComparison.Ordinal) ? "\r\n" : "\n";
        string[] lines = content.Split(new[] { newline }, StringSplitOptions.None);
        Dictionary<string, HashSet<string>> synchronizedFiles = new(StringComparer.OrdinalIgnoreCase);

        foreach (BaselineBlock block in EnumerateBaselineBlocks(lines))
        {
            if (!codesToKeep.Contains(block.Code))
            {
                foreach (string sectionFile in block.SectionFiles)
                {
                    AddSynchronizedFile(synchronizedFiles, sectionFile, block.Code);
                }
            }
            else if (activeFilesByCode is not null)
            {
                IReadOnlySet<string> activeFilesForCode = GetActiveFilesForCode(activeFilesByCode, block.Code);

                foreach (string sectionFile in block.SectionFiles.Where(
                    sectionFile => !activeFilesForCode.Contains(NormalizeEditorConfigPath(sectionFile))
                ))
                {
                    AddSynchronizedFile(synchronizedFiles, sectionFile, block.Code);
                }
            }
        }

        return synchronizedFiles.ToDictionary(
            x => x.Key,
            x => (IReadOnlySet<string>)x.Value,
            StringComparer.OrdinalIgnoreCase
        );
    }

    private static IEnumerable<BaselineBlock> EnumerateBaselineBlocks(string[] lines)
    {
        for (int i = 0; i < lines.Length; i++)
        {
            Match headerMatch = s_baselineSectionHeaderRegex.Match(lines[i]);
            if (!headerMatch.Success)
            {
                continue;
            }

            int diagIndex = i + 1;
            while (diagIndex < lines.Length && string.IsNullOrWhiteSpace(lines[diagIndex]))
            {
                diagIndex++;
            }

            if (diagIndex >= lines.Length)
            {
                continue;
            }

            Match diagMatch = s_baselineDiagnosticRegex.Match(lines[diagIndex]);
            if (!diagMatch.Success)
            {
                continue;
            }

            int blockEnd = diagIndex + 1;
            while (blockEnd < lines.Length && string.IsNullOrWhiteSpace(lines[blockEnd]))
            {
                blockEnd++;
            }

            string[] sectionFiles = headerMatch.Groups["files"].Value
                .Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries);

            yield return new BaselineBlock(i, blockEnd, diagMatch.Groups[1].Value, sectionFiles);
        }
    }

    private static IReadOnlySet<string> GetActiveFilesForCode(
        IReadOnlyDictionary<string, IReadOnlySet<string>> activeFilesByCode,
        string code)
    {
        return activeFilesByCode.TryGetValue(code, out IReadOnlySet<string>? files)
            ? files
            : new HashSet<string>(StringComparer.OrdinalIgnoreCase);
    }

    private static void AddSynchronizedFile(Dictionary<string, HashSet<string>> synchronizedFiles, string filePath, string code)
    {
        if (!synchronizedFiles.TryGetValue(filePath, out HashSet<string>? codes))
        {
            codes = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            synchronizedFiles[filePath] = codes;
        }

        codes.Add(code);
    }

    private static string NormalizeEditorConfigPath(string path)
    {
        return path.Replace('\\', '/');
    }

    private readonly record struct BaselineBlock(
        int HeaderIndex,
        int BlockEndIndex,
        string Code,
        string[] SectionFiles
    );
}
