// Copyright (c) 2026 kurnakovv
// This file is licensed under the MIT License.
// See the LICENSE file in the project root for full license information.

namespace Biak.ConsoleApp.Constants;

/// <summary>
/// All .editorconfig constants.
/// </summary>
public static class EditorconfigConstant
{
    /// <summary>
    /// The text at the beginning of the .editorconfig file when biak is configured.
    /// </summary>
    public const string UP_TEXT = "# ⚠️ Attention ⚠️\r\n" +
        "#\r\n# This file is managed by the \"biak\" tool.\r\n" +
        "# All changes are generated from the \".biak\" folder.\r\n" +
        "# Do not edit this file manually - your changes will be overwritten.\r\n" +
        "# To modify its contents, update the sources inside \".biak\" folder.\r\n" +
        "#\r\n# To learn more about biak, visit: https://github.com/kurnakovv/biak\r\n\r\n";

    /// <summary>
    /// The text at the bottom of the .editorconfig file when biak is configured.
    /// </summary>
    public const string BOTTOM_TEXT = "\r\n# ⚠️ Attention ⚠️\r\n"
        + "#\r\n"
        + "# This file is managed by biak.\r\n"
        + "# Do not edit it manually - your changes will be overwritten.\r\n"
        + "# See the note at the top ☝️ of the file for details.\r\n";
}
