// Copyright (c) 2026 kurnakovv
// This file is licensed under the MIT License.
// See the LICENSE file in the project root for full license information.

namespace Biak.ConsoleApp.Constants;

#pragma warning disable RCS1266 // Use raw string literal
/// <summary>
/// All .editorconfig constants.
/// </summary>
public static class EditorconfigConstant
{
    /// <summary>
    /// The text at the beginning of the .editorconfig file when biak is configured.
    /// </summary>
    public const string UP_TEXT = @"# ⚠️ Attention ⚠️
#
# This file is managed by the ""biak"" tool.
# All changes are generated from the "".biak"" folder.
# Do not edit this file manually - your changes will be overwritten.
# To modify its contents, update the sources inside "".biak"" folder.
#
# To learn more about biak, visit: https://github.com/kurnakovv/biak

";

    /// <summary>
    /// The text at the bottom of the .editorconfig file when biak is configured.
    /// </summary>
    public const string BOTTOM_TEXT = @"
# ⚠️ Attention ⚠️
#
# This file is managed by biak.
# Do not edit it manually - your changes will be overwritten.
# See the note at the top ☝️ of the file for details.
";
}

#pragma warning restore RCS1266 // Use raw string literal
