name: CodeCov

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'ReadMe.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'ReadMe.md'
      - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test Unit Tests with coverage
        run: dotnet test tests/Biak.ConsoleApp.UnitTests/Biak.ConsoleApp.UnitTests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage;Format=cobertura" --results-directory ./TestResults/Unit
      - name: Test Integration Tests with coverage
        run: dotnet test tests/Biak.ConsoleApp.IntegrationTests/Biak.ConsoleApp.IntegrationTests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage;Format=cobertura" --results-directory ./TestResults/Integration
      - name: Upload Unit Test Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./TestResults/Unit/**/coverage.cobertura.xml
          flags: unit-tests
          name: unit-tests-coverage
          verbose: true
      - name: Upload Integration Test Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./TestResults/Integration/**/coverage.cobertura.xml
          flags: integration-tests
          name: integration-tests-coverage
          verbose: true